sync

diff --git a/applications/luci-app-openclash/root/etc/init.d/openclash b/applications/luci-app-openclash/root/etc/init.d/openclash
--- a/applications/luci-app-openclash/root/etc/init.d/openclash
+++ b/applications/luci-app-openclash/root/etc/init.d/openclash
@@ -146,22 +146,24 @@ revert_dns() {
       
       if [ "$4" == "0" ] || [ -z "$4" ] || [ -z "$(uci -q show dhcp.@dnsmasq[0].server)" ]; then
          uci -q set dhcp.@dnsmasq[0].noresolv=0
-         if [ -n "$5" ]; then
+         if [ -n "$5" ] && [ -n "$(grep nameserver $5)" ]; then
             uci -q set dhcp.@dnsmasq[0].resolvfile="$5"
-         elif [ -n "$3" ]; then
+            uci -q set openclash.config.default_resolvfile="$5"
+         elif [ -n "$3" ] && [ -n "$(grep nameserver $3)" ]; then
             uci -q set dhcp.@dnsmasq[0].resolvfile="$3"
+            uci -q set openclash.config.default_resolvfile="$3"
          fi
          uci -q commit dhcp
          /etc/init.d/dnsmasq restart >/dev/null 2>&1
          masq_port=$(uci -q get dhcp.@dnsmasq[0].port)
-         if [ "$(nslookup www.baidu.com 127.0.0.1:${masq_port} >/dev/null 2>&1 || echo $?)" = "1" ]; then
+         if [ "$(nslookup www.apple.com 127.0.0.1:${masq_port} >/dev/null 2>&1 || echo $?)" = "1" ]; then
             uci -q set openclash.config.default_resolvfile="/tmp/resolv.conf.auto"
             rm -rf /tmp/resolv.conf.auto
             touch /tmp/resolv.conf.auto 2>/dev/null
             cat >> "/tmp/resolv.conf.auto" <<-EOF
 # Interface lan
-nameserver 114.114.114.114
 nameserver 119.29.29.29
+nameserver 8.8.8.8
 EOF
             uci -q set dhcp.@dnsmasq[0].resolvfile="/tmp/resolv.conf.auto"
          fi
@@ -1330,45 +1332,6 @@ if [ "$ipv6_enable" -eq 1 ]; then
    esac
 fi
 
-#lan interfaces
-if [ -n "$FW4" ]; then
-   lan_ints=$(nft list chain inet fw4 input |grep -e "jump input_lan" 2>/dev/null |awk '{for (i=1;i<=NF;i++){if ($i ~ /iifname/ && $(i+1) != "{") {print $(i+1)} if ($i ~ /iifname/ && $(i+1) == "{"){for (j=i+1;j<=NF;j++){if ($j~ /}/) {out="";for (k=i+1;k<=j;k++){out=out" "$k};print out}}}}}' 2>/dev/null |sed 's/"//g'|sed 's/{//g'|sed 's/}//g'|sed 's/,//g')
-   if [ -z "$lan_ints" ]; then
-      lan_ints=$(ip route |grep 'default' |awk '{print $5}' |head -1 2>/dev/null)
-      if [ -z "$(echo "$(ls -l /sys/class/net/ 2>/dev/null |awk '{print $9}' 2>/dev/null)" |grep -E ^${lan_ints}$)" ]; then
-         lan_ints=""
-      fi
-   fi
-   lan6_ints=$(nft list chain inet fw4 input |grep -e "jump input_lan" 2>/dev/null |awk '{for (i=1;i<=NF;i++){if ($i ~ /iifname/ && $(i+1) != "{") {print $(i+1)} if ($i ~ /iifname/ && $(i+1) == "{"){for (j=i+1;j<=NF;j++){if ($j~ /}/) {out="";for (k=i+1;k<=j;k++){out=out" "$k};print out}}}}}' 2>/dev/null |sed 's/"//g'|sed 's/{//g'|sed 's/}//g'|sed 's/,//g')
-   if [ -z "$lan6_ints" ]; then
-      lan6_ints=$(ip route |grep 'default' |awk '{print $5}' |head -1 2>/dev/null)
-      if [ -z "$(echo "$(ls -l /sys/class/net/ 2>/dev/null |awk '{print $9}' 2>/dev/null)" |grep -E ^${lan6_ints}$)" ]; then
-         lan6_ints=""
-      fi
-   fi
-else
-   lan_ints=$(iptables-save -t filter |grep -e "-j zone_lan_input" 2>/dev/null |awk '{for (i=1;i<=NF;i++) {if ($i ~ /-i/) {print $(i+1)}}}' 2>/dev/null)
-   if [ -z "$lan_ints" ]; then
-      lan_ints=$(ip route |grep 'default' |awk '{print $5}' |head -1 2>/dev/null)
-      if [ -z "$(echo "$(ls -l /sys/class/net/ 2>/dev/null |awk '{print $9}' 2>/dev/null)" |grep -E ^${lan_ints}$)" ]; then
-         lan_ints=""
-      fi
-   fi
-   lan6_ints=$(ip6tables-save -t filter |grep -e "-j zone_lan_input" 2>/dev/null |awk '{for (i=1;i<=NF;i++) {if ($i ~ /-i/) {print $(i+1)}}}' 2>/dev/null)
-   if [ -z "$lan6_ints" ]; then
-      lan6_ints=$(ip route |grep 'default' |awk '{print $5}' |head -1 2>/dev/null)
-      if [ -z "$(echo "$(ls -l /sys/class/net/ 2>/dev/null |awk '{print $9}' 2>/dev/null)" |grep -E ^${lan6_ints}$)" ]; then
-         lan6_ints=""
-      fi
-   fi
-fi
-if [ -z "$lan_ints" ]; then
-   LOG_OUT "Tip: Can't Get IPv4 LAN Interfaces, Please Verify The Firewall's LAN Zone Name is lan..."
-fi
-if [ -z "$lan6_ints" ]; then
-   LOG_OUT "Tip: Can't Get IPv6 LAN Interfaces, Please Verify The Firewall's LAN Zone Name is lan..."
-fi
-
 if [ -n "$FW4" ]; then
    LOG_OUT "Tip: Firewall4 was Detected, Use NFTABLE Rules..."
    if [ "$china_ip_route" = "1" ] || [ "$disable_udp_quic" = "1" ]; then
@@ -1516,7 +1479,7 @@ if [ -n "$FW4" ]; then
          nft add rule inet fw4 openclash_wan_input udp dport {$proxy_port,$tproxy_port,$cn_port,$http_port,$socks_port,$mixed_port,$dns_port} counter reject
          nft add rule inet fw4 openclash_wan_input tcp dport {$proxy_port,$tproxy_port,$cn_port,$http_port,$socks_port,$mixed_port,$dns_port} counter reject
       else
-         LOG_OUT "Tip: Can't Get IPv4 WAN Interfaces, Please Verify The Firewall's WAN Zone Name is wan, Ignore This IF The Device Does not Have a WAN Interfaces..."
+         LOG_OUT "Warning: Can't Settting Only Intranet Allowed Function, Get IPv4 WAN Interfaces error, Please Verify The Firewall's WAN Zone Name is wan, Ignore This IF The Device Does not Have a WAN Interfaces..."
       fi
    fi
 
@@ -1584,14 +1547,7 @@ if [ -n "$FW4" ]; then
       #tcp
       nft 'add chain inet fw4 openclash' 2>/dev/null
       nft 'flush chain inet fw4 openclash' 2>/dev/null
-      if [ -n "$lan_ints" ]; then
-         nft add rule inet fw4 openclash iifname lo ip daddr @localnetwork counter return 2>/dev/null
-         for lan_int in $lan_ints; do
-            nft add rule inet fw4 openclash iifname "$lan_int" ip daddr @localnetwork counter return
-         done >/dev/null 2>&1
-      else
-         nft add rule inet fw4 openclash ip daddr @localnetwork counter return 2>/dev/null
-      fi
+      nft add rule inet fw4 openclash ip daddr @localnetwork counter return 2>/dev/null
       if [ -z "$en_mode_tun" ] && [ "$en_mode" = "fake-ip" ]; then
           nft add rule inet fw4 openclash ip protocol tcp ip daddr { "$fakeip_range" } counter redirect to "$proxy_port" 2>/dev/null
       fi
@@ -1631,14 +1587,7 @@ if [ -n "$FW4" ]; then
             nft 'add chain inet fw4 openclash_upnp' 2>/dev/null
             nft 'flush chain inet fw4 openclash_upnp' 2>/dev/null
             upnp_exclude
-            if [ -n "$lan_ints" ]; then
-               nft add rule inet fw4 openclash_mangle iifname lo ip daddr @localnetwork counter return 2>/dev/null
-               for lan_int in $lan_ints; do
-                  nft add rule inet fw4 openclash_mangle iifname "$lan_int" ip daddr @localnetwork counter return
-               done >/dev/null 2>&1
-            else
-               nft add rule inet fw4 openclash_mangle ip daddr @localnetwork counter return 2>/dev/null
-            fi
+            nft add rule inet fw4 openclash_mangle ip daddr @localnetwork counter return 2>/dev/null
             nft 'add rule inet fw4 openclash_mangle udp dport 53 counter return' 2>/dev/null
             if [ "$en_mode" = "fake-ip" ]; then
                nft add rule inet fw4 openclash_mangle meta l4proto { udp } ip daddr { "$fakeip_range" } mark set "$PROXY_FWMARK" tproxy ip to 127.0.0.1:"$tproxy_port" counter accept 2>/dev/null
@@ -1776,14 +1725,7 @@ if [ -n "$FW4" ]; then
 
       #其他流量
       nft 'add rule inet fw4 openclash_mangle meta l4proto {tcp,udp} iifname utun counter return' 2>/dev/null
-      if [ -n "$lan_ints" ]; then
-         nft add rule inet fw4 openclash_mangle iifname lo ip daddr @localnetwork counter return 2>/dev/null
-         for lan_int in $lan_ints; do
-            nft add rule inet fw4 openclash_mangle iifname "$lan_int" ip daddr @localnetwork counter return
-         done >/dev/null 2>&1
-      else
-         nft add rule inet fw4 openclash_mangle ip daddr @localnetwork counter return 2>/dev/null
-      fi
+      nft add rule inet fw4 openclash_mangle ip daddr @localnetwork counter return 2>/dev/null
       nft 'add rule inet fw4 openclash_mangle ip saddr @localnetwork meta l4proto {tcp,udp} th sport @lan_ac_black_ports counter return' 2>/dev/null
       nft 'add rule inet fw4 openclash_mangle ip daddr @wan_ac_black_ips counter return' 2>/dev/null
       nft 'add rule inet fw4 openclash_mangle ip saddr @lan_ac_black_ips counter return' 2>/dev/null
@@ -1985,14 +1927,7 @@ if [ -n "$FW4" ]; then
          #tcp
          nft 'add chain inet fw4 openclash_v6' 2>/dev/null
          nft 'flush chain inet fw4 openclash_v6' 2>/dev/null
-         if [ -n "$lan6_ints" ]; then
-            nft add rule inet fw4 openclash_v6 iifname lo ip6 daddr @localnetwork6 counter return 2>/dev/null
-            for lan6_int in $lan6_ints; do
-               nft add rule inet fw4 openclash_v6 iifname "$lan6_int" ip6 daddr @localnetwork6 counter return
-            done >/dev/null 2>&1
-         else
-            nft add rule inet fw4 openclash_v6 ip6 daddr @localnetwork6 counter return 2>/dev/null
-         fi
+         nft add rule inet fw4 openclash_v6 ip6 daddr @localnetwork6 counter return 2>/dev/null
          nft 'add rule inet fw4 openclash_v6 ip6 saddr @localnetwork6 meta nfproto {ipv6} sport @lan_ac_black_ports counter return' 2>/dev/null
          nft 'add rule inet fw4 openclash_v6 ip6 daddr @wan_ac_black_ipv6s counter return' 2>/dev/null
          nft 'add rule inet fw4 openclash_v6 ip6 saddr @lan_ac_black_ipv6s counter return' 2>/dev/null
@@ -2048,14 +1983,7 @@ if [ -n "$FW4" ]; then
       if [ "$enable_v6_udp_proxy" -eq 1 ] || [ "$ipv6_mode" -eq 0 ] || [ "$ipv6_mode" -eq 2 ]; then
          nft 'add chain inet fw4 openclash_mangle_v6' 2>/dev/null
          nft 'flush chain inet fw4 openclash_mangle_v6' 2>/dev/null
-         if [ -n "$lan6_ints" ]; then
-            nft add rule inet fw4 openclash_mangle_v6 iifname lo ip6 daddr @localnetwork6 counter return 2>/dev/null
-            for lan6_int in $lan6_ints; do
-               nft add rule inet fw4 openclash_mangle_v6 iifname "$lan6_int" ip6 daddr @localnetwork6 counter return
-            done >/dev/null 2>&1
-         else
-            nft add rule inet fw4 openclash_mangle_v6 ip6 daddr @localnetwork6 counter return 2>/dev/null
-         fi
+         nft add rule inet fw4 openclash_mangle_v6 ip6 daddr @localnetwork6 counter return 2>/dev/null
          nft 'add rule inet fw4 openclash_mangle_v6 meta nfproto {ipv6} udp dport 53 counter return' 2>/dev/null
          nft 'add rule inet fw4 openclash_mangle_v6 ip6 saddr @localnetwork6 meta nfproto {ipv6} sport @lan_ac_black_ports counter return' 2>/dev/null
          nft 'add rule inet fw4 openclash_mangle_v6 ip6 daddr @wan_ac_black_ipv6s counter return' 2>/dev/null
@@ -2178,7 +2106,7 @@ if [ -n "$FW4" ]; then
             nft add rule inet fw4 openclash_wan6_input udp dport {$proxy_port,$tproxy_port,$cn_port,$http_port,$socks_port,$mixed_port,$dns_port} counter reject 2>/dev/null
             nft add rule inet fw4 openclash_wan6_input tcp dport {$proxy_port,$tproxy_port,$cn_port,$http_port,$socks_port,$mixed_port,$dns_port} counter reject 2>/dev/null
          else
-            LOG_OUT "Tip: Can't Get IPv6 WAN Interfaces, Please Verify The Firewall's WAN Zone Name is wan, Ignore This IF The Device Does not Have a WAN Interfaces..."
+            LOG_OUT "Warning: Can't Settting Only Intranet Allowed Function, Get IPv6 WAN Interfaces error, Please Verify The Firewall's WAN Zone Name is wan, Ignore This IF The Device Does not Have a WAN Interfaces..."
          fi
       fi
    fi 2>/dev/null
@@ -2300,7 +2228,7 @@ else
          iptables -t filter -A openclash_wan_input -p udp -m multiport --dport "$proxy_port,$tproxy_port,$cn_port,$http_port,$socks_port,$mixed_port,$dns_port" -j REJECT >/dev/null 2>&1
          iptables -t filter -A openclash_wan_input -p tcp -m multiport --dport "$proxy_port,$tproxy_port,$cn_port,$http_port,$socks_port,$mixed_port,$dns_port" -j REJECT >/dev/null 2>&1
       else
-         LOG_OUT "Tip: Can't Get IPv4 WAN Interfaces, Please Verify The Firewall's WAN Zone Name is wan, Ignore This IF The Device Does not Have a WAN Interfaces..."
+         LOG_OUT "Warning: Can't Settting Only Intranet Allowed Function, Get IPv4 WAN Interfaces error, Please Verify The Firewall's WAN Zone Name is wan, Ignore This IF The Device Does not Have a WAN Interfaces..."
       fi
    fi
 
@@ -2390,14 +2318,7 @@ else
       #tcp
       iptables -t nat -N openclash
       iptables -t nat -F openclash
-      if [ -n "$lan_ints" ]; then
-         iptables -t nat -A openclash -i lo -m set --match-set localnetwork dst -j RETURN
-         for lan_int in $lan_ints; do
-            iptables -t nat -A openclash -i "$lan_int" -m set --match-set localnetwork dst -j RETURN
-         done
-      else
-         iptables -t nat -A openclash -m set --match-set localnetwork dst -j RETURN
-      fi
+      iptables -t nat -A openclash -m set --match-set localnetwork dst -j RETURN
       if [ -z "$en_mode_tun" ] && [ "$en_mode" = "fake-ip" ]; then
          iptables -t nat -A openclash -p tcp -d "$fakeip_range" -j REDIRECT --to-ports "$proxy_port"
       fi
@@ -2438,14 +2359,7 @@ else
             iptables -t mangle -N openclash_upnp
             iptables -t mangle -F openclash_upnp
             upnp_exclude
-            if [ -n "$lan_ints" ]; then
-               iptables -t mangle -A openclash -i lo -m set --match-set localnetwork dst -j RETURN
-               for lan_int in $lan_ints; do
-                  iptables -t mangle -A openclash -i "$lan_int" -m set --match-set localnetwork dst -j RETURN
-               done >/dev/null 2>&1
-            else
-               iptables -t mangle -A openclash -m set --match-set localnetwork dst -j RETURN
-            fi
+            iptables -t mangle -A openclash -m set --match-set localnetwork dst -j RETURN
             iptables -t mangle -A openclash -p udp --dport 53 -j RETURN >/dev/null 2>&1
             if [ "$en_mode" = "fake-ip" ]; then
                iptables -t mangle -A openclash -p udp -d "$fakeip_range" -j TPROXY --on-port "$tproxy_port" --tproxy-mark "$PROXY_FWMARK"
@@ -2583,14 +2497,7 @@ else
       upnp_exclude
       #其他流量
       iptables -t mangle -A openclash -i utun -j RETURN >/dev/null 2>&1
-      if [ -n "$lan_ints" ]; then
-         iptables -t mangle -A openclash -i lo -m set --match-set localnetwork dst -j RETURN
-         for lan_int in $lan_ints; do
-            iptables -t mangle -A openclash -i "$lan_int" -m set --match-set localnetwork dst -j RETURN
-         done >/dev/null 2>&1
-      else
-         iptables -t mangle -A openclash -m set --match-set localnetwork dst -j RETURN
-      fi
+      iptables -t mangle -A openclash -m set --match-set localnetwork dst -j RETURN
       iptables -t mangle -A openclash -m set --match-set localnetwork src -m set --match-set lan_ac_black_ports src -j RETURN >/dev/null 2>&1
       iptables -t mangle -A openclash -m set --match-set wan_ac_black_ips dst -j RETURN >/dev/null 2>&1
       iptables -t mangle -A openclash -m set --match-set lan_ac_black_ips src -j RETURN >/dev/null 2>&1
@@ -2787,14 +2694,7 @@ else
          #tcp
          ip6tables -t nat -N openclash
          ip6tables -t nat -F openclash
-         if [ -n "$lan6_ints" ]; then
-            ip6tables -t nat -A openclash -i lo -m set --match-set localnetwork6 dst -j RETURN
-            for lan6_int in $lan6_ints; do
-               ip6tables -t nat -A openclash -i "$lan6_int" -m set --match-set localnetwork6 dst -j RETURN
-            done
-         else
-            ip6tables -t nat -A openclash -m set --match-set localnetwork6 dst -j RETURN
-         fi
+         ip6tables -t nat -A openclash -m set --match-set localnetwork6 dst -j RETURN
          ip6tables -t nat -A openclash -m set --match-set localnetwork6 src -m set --match-set lan_ac_black_ports src -j RETURN >/dev/null 2>&1
          ip6tables -t nat -A openclash -m set --match-set wan_ac_black_ipv6s dst -j RETURN >/dev/null 2>&1
          ip6tables -t nat -A openclash -m set --match-set lan_ac_black_ipv6s src -j RETURN >/dev/null 2>&1
@@ -2844,14 +2744,7 @@ else
       if [ "$enable_v6_udp_proxy" -eq 1 ] || [ "$ipv6_mode" -eq 0 ] || [ "$ipv6_mode" -eq 2 ]; then
          ip6tables -t mangle -N openclash
          ip6tables -t mangle -F openclash
-         if [ -n "$lan6_ints" ]; then
-            ip6tables -t mangle -A openclash -i lo -m set --match-set localnetwork6 dst -j RETURN
-            for lan6_int in $lan6_ints; do
-               ip6tables -t mangle -A openclash -i "$lan6_int" -m set --match-set localnetwork6 dst -j RETURN
-            done >/dev/null 2>&1
-         else
-            ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
-         fi
+         ip6tables -t mangle -A openclash -m set --match-set localnetwork6 dst -j RETURN
          ip6tables -t mangle -A openclash -p udp --dport 53 -j RETURN >/dev/null 2>&1
          ip6tables -t mangle -A openclash -m set --match-set localnetwork6 src -m set --match-set lan_ac_black_ports src -j RETURN >/dev/null 2>&1
          ip6tables -t mangle -A openclash -m set --match-set wan_ac_black_ipv6s dst -j RETURN >/dev/null 2>&1
@@ -2972,7 +2865,7 @@ else
             ip6tables -t filter -A openclash_wan_input -p udp -m multiport --dport "$proxy_port,$tproxy_port,$cn_port,$http_port,$socks_port,$mixed_port,$dns_port" -j REJECT >/dev/null 2>&1
             ip6tables -t filter -A openclash_wan_input -p tcp -m multiport --dport "$proxy_port,$tproxy_port,$cn_port,$http_port,$socks_port,$mixed_port,$dns_port" -j REJECT >/dev/null 2>&1
          else
-            LOG_OUT "Tip: Can't Get IPv6 WAN Interfaces, Please Verify The Firewall's WAN Zone Name is wan, Ignore This IF The Device Does not Have a WAN Interfaces..."
+            LOG_OUT "Warning: Can't Settting Only Intranet Allowed Function, Get IPv6 WAN Interfaces error, Please Verify The Firewall's WAN Zone Name is wan, Ignore This IF The Device Does not Have a WAN Interfaces..."
          fi
       fi
    fi 2>/dev/null
