sync

diff --git a/applications/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic b/applications/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
--- a/applications/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
+++ b/applications/luci-app-unblockneteasemusic/root/etc/init.d/unblockneteasemusic
@@ -76,12 +76,13 @@ start_service() {
 	local update_time
 	config_get update_time "config" "update_time" "3"
 	sed -i "/$NAME/d" /etc/crontabs/root
-	is_enabled "config" "auto_update" && echo "0 ${update_time} * * * $UNM_DIR/update.sh update_core" >> "/etc/crontabs/root"
+	echo -e "30 2 * * * /etc/init.d/unblockneteasemusic restart" >> "/etc/crontabs/root"
+	! is_enabled "config" "auto_update" || echo -e "0 ${update_time} * * * $UNM_DIR/update.sh update_core" >> "/etc/crontabs/root"
 	/etc/init.d/cron restart
 
 	mkdir -p "$RUN_DIR"
-	[ ! -s "$UNM_DIR/core/app.js" ] && { rm -f "$UNM_DIR/local_ver"; sh "$UNM_DIR/update.sh" "update_core_non_restart"; }
-	[ ! -s "$UNM_DIR/core/app.js" ] && { echo "Core Not Found, please download it before starting." >> "$RUN_DIR/run.log"; return 1; }
+	[ -s "$UNM_DIR/core/app.js" ] || { rm -f "$UNM_DIR/local_ver"; sh "$UNM_DIR/update.sh" "update_core_non_restart"; }
+	[ -s "$UNM_DIR/core/app.js" ] || { echo "Core Not Found, please download it before starting." >> "$RUN_DIR/run.log"; return 1; }
 
 	procd_open_instance "$NAME"
 	procd_set_param command node "$UNM_DIR/core/app.js"
@@ -154,7 +155,7 @@ start_service() {
 			ipset=/clientlog.music.163.com/neteasemusic
 			ipset=/clientlog3.music.163.com/neteasemusic
 		EOF
-		/etc/init.d/dnsmasq restart 2>"/dev/null"
+		/etc/init.d/dnsmasq reload 2>"/dev/null"
 
 		ipset create "acl_neteasemusic_http" hash:ip
 		ipset create "acl_neteasemusic_https" hash:ip
@@ -189,7 +190,7 @@ start_service() {
 			address=/clientlog3.music.163.com/${lan_addr}
 			address=/music.httpdns.c.163.com/0.0.0.0
 		EOF
-		/etc/init.d/dnsmasq restart 2>"/dev/null"
+		/etc/init.d/dnsmasq reload 2>"/dev/null"
 
 		ip route add "223.252.199.10" dev lo
 	fi
@@ -224,18 +225,18 @@ stop_service() {
 	echo > "$RUN_DIR/fw3.include"
 
 	rm -f "/tmp/dnsmasq.d/dnsmasq-$NAME.conf"
-	/etc/init.d/dnsmasq restart 2>"/dev/null"
+	/etc/init.d/dnsmasq reload 2>"/dev/null"
 
 	ip route del "223.252.199.10" 2>"/dev/null"
 
 	rm -f "$RUN_DIR/run.log"
 }
 
-restart_service() {
+reload_service() {
 	stop
 	start
 }
 
 service_triggers() {
-	procd_add_restart_trigger "$NAME"
+	procd_add_reload_trigger "$NAME"
 }
